name: Save Logs Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Custom Script
        run: |
          echo "Running a custom script"
          echo "Step 1" >> custom_log.txt
          echo "Step 2" >> custom_log.txt

      - name: Upload Logs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-log
          path: custom_log.txt
