name: Debug Log Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Debug Logs
        run: |
          echo "::debug::Starting the build process"
          echo "::debug::Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "::debug::Listing files in the directory"
          ls -la
